# Generated by Django 5.2 on 2025-04-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VENITHfastcars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=260)),
                ('discount', models.FloatField()),
            ],
        ),
    ]
