# Generated by Django 5.2 on 2025-05-06 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VENITHfastcars', '0005_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='VENITHfastcars.product'),
            preserve_default=False,
        ),
    ]
